require('gamemode')
require('libraries/timers')
require('libraries/popups')
require('libraries/notifications')

require('internal/util')

require('upgrades')
require('mechanics')
require('orders')
require('builder')
require('buildinghelper')


function Precache( context )
	--Precache Special Towers
	PrecacheUnitByNameSync( "tower_watchtower", context )
	PrecacheUnitByNameSync( "tower_heroicshrine", context )
	PrecacheUnitByNameSync( "tower_treasurebox", context )
	PrecacheUnitByNameSync( "tower_barrack", context )
	PrecacheUnitByNameSync( "tower_watchtower", context )
	
	--Precache Units
	PrecacheUnitByNameSync( "fort_goodguys", context )
	PrecacheUnitByNameSync( "fort_badguys", context )
	PrecacheUnitByNameSync( "npc_creature_footman", context )
	PrecacheUnitByNameSync( "npc_creature_defender", context )
	PrecacheUnitByNameSync( "npc_creature_sniper", context )
	PrecacheUnitByNameSync( "npc_creature_mortarteam", context )
	PrecacheUnitByNameSync( "npc_creature_gryphonrider", context )
	PrecacheUnitByNameSync( "npc_creature_crusader", context )
	PrecacheUnitByNameSync( "npc_creature_paladin", context )
	PrecacheUnitByNameSync( "npc_creature_warlock", context )
	PrecacheUnitByNameSync( "npc_creature_murloc_assassin", context )
	PrecacheUnitByNameSync( "npc_creature_suumpmolk", context )
	PrecacheUnitByNameSync( "npc_creature_ancient_hydra", context )
	PrecacheUnitByNameSync( "npc_creature_winged_serpent", context )
	PrecacheUnitByNameSync( "npc_creature_naga_guardian", context )
	PrecacheUnitByNameSync( "npc_creature_dragon_turtle", context )
	PrecacheUnitByNameSync( "npc_creature_naga_siren", context )
	PrecacheUnitByNameSync( "npc_creature_naga_lobster", context )
	PrecacheUnitByNameSync( "npc_creature_archer", context )
	PrecacheUnitByNameSync( "npc_creature_master_archer", context )
	PrecacheUnitByNameSync( "npc_creature_elder_blademaster", context )
	PrecacheUnitByNameSync( "npc_creature_bloodthirster", context )
	PrecacheUnitByNameSync( "npc_creature_dragonhawk_rider", context )
	PrecacheUnitByNameSync( "npc_creature_sorceress", context )
	PrecacheUnitByNameSync( "npc_creature_wizard", context )
	PrecacheUnitByNameSync( "npc_creature_satyr", context )
	PrecacheUnitByNameSync( "npc_creature_quill_demon", context )
	PrecacheUnitByNameSync( "npc_creature_chaos_champion", context )
	PrecacheUnitByNameSync( "npc_creature_succubus", context )
	PrecacheUnitByNameSync( "npc_creature_blood_fiend", context )
	PrecacheUnitByNameSync( "npc_creature_red_dragon", context )
	PrecacheUnitByNameSync( "npc_creature_infernal", context )
	PrecacheUnitByNameSync( "npc_creature_zombie", context )
	PrecacheUnitByNameSync( "npc_creature_suffocated_zombie", context )
	PrecacheUnitByNameSync( "npc_creature_plague_bearer", context )
	PrecacheUnitByNameSync( "npc_creature_mighty_necromancer", context )
	PrecacheUnitByNameSync( "npc_creature_lich_king", context )
	PrecacheUnitByNameSync( "npc_creature_vampire_lord", context )
	PrecacheUnitByNameSync( "npc_creature_banshee", context )
	PrecacheUnitByNameSync( "npc_creature_flesh_golem", context )
	PrecacheUnitByNameSync( "npc_creature_frost_wyrm", context )
	PrecacheUnitByNameSync( "npc_creature_greater_skeletal_mage", context )
	PrecacheUnitByNameSync( "npc_creature_greater_skeleton_archer", context )
	PrecacheUnitByNameSync( "npc_creature_skeleton_warrior", context )
	PrecacheUnitByNameSync( "npc_creature_skeleton_general", context )
	PrecacheUnitByNameSync( "npc_creature_mutation", context )
	PrecacheUnitByNameSync( "npc_creature_veteran_axemaster", context )
	PrecacheUnitByNameSync( "npc_creature_shaman", context )
	PrecacheUnitByNameSync( "npc_creature_troll_beserker", context )
	PrecacheUnitByNameSync( "npc_creature_troll_trapper", context )
	PrecacheUnitByNameSync( "npc_creature_wyvern_rider", context )
	PrecacheUnitByNameSync( "npc_creature_kodo", context )
	PrecacheUnitByNameSync( "npc_creature_spellbreaker_kodo", context )
	PrecacheUnitByNameSync( "npc_creature_defensive_kodo", context )
	PrecacheUnitByNameSync( "npc_creature_offensive_kodo", context )
	PrecacheUnitByNameSync( "npc_creature_catapult", context )
	PrecacheUnitByNameSync( "npc_creature_ballista", context )
	PrecacheUnitByNameSync( "npc_creature_frost_wolf", context )
	PrecacheUnitByNameSync( "npc_creature_polar_bear", context )
	PrecacheUnitByNameSync( "npc_creature_magnataur", context )
	PrecacheUnitByNameSync( "npc_creature_hrimthrusa", context )
	PrecacheUnitByNameSync( "npc_creature_ice_troll_shadow_priest", context )
	PrecacheUnitByNameSync( "npc_creature_ice_troll_witch_doctor", context )
	PrecacheUnitByNameSync( "npc_creature_ice_wandigoo", context )
	PrecacheUnitByNameSync( "npc_creature_ice_ancient_wandigoo", context )
	PrecacheUnitByNameSync( "npc_creature_azure_drake", context )
	PrecacheUnitByNameSync( "npc_creature_ice_queen", context )

	--Precache Others
	PrecacheUnitByNameSync( "npc_dummy", context )
	PrecacheUnitByNameSync( "npc_dummy_world_freezer", context )
	PrecacheUnitByNameSync( "npc_dota_hero_axe", context )
	PrecacheUnitByNameSync( "npc_dota_hero_windrunner", context )
	PrecacheUnitByNameSync( "npc_dota_hero_warlock", context )
	PrecacheUnitByNameSync( "npc_dota_hero_necrophos", context )
	PrecacheUnitByNameSync( "npc_dota_hero_huskar", context )
	PrecacheUnitByNameSync( "npc_dota_hero_tusk", context )
	
	--Precache Particles
	PrecacheResource( "particle_folder", "particles/units/heroes/hero_pugna/", context )
	PrecacheResource( "particle_folder", "particles/units/heroes/hero_death_prophet/", context )
	PrecacheResource( "particle_folder", "particles/units/heroes/hero_abaddon/", context )
	PrecacheResource( "particle_folder", "particles/units/heroes/hero_orge_magi/", context )
	PrecacheResource( "particle_folder", "particles/units/heroes/hero_luna/", context )
	
	PrecacheResource( "particle", "particles/dire_fx/dire_ancient_base001_destruction_d.vpcf", context )
	PrecacheResource( "particle", "particles/dire_fx/dire_ancient_base001_destruction_e.vpcf", context )
	PrecacheResource( "particle", "particles/dire_fx/dire_ancient_base001_destruction_f.vpcf", context )
	PrecacheResource( "particle", "particles/dire_fx/dire_ancient_base001_destruction_g.vpcf", context )
	PrecacheResource( "particle", "particles/dire_fx/dire_ancient_base001_destruction_h.vpcf", context )
	PrecacheResource( "particle", "particles/dire_fx/dire_ancient_base001_destruction_i.vpcf", context )
	PrecacheResource( "particle", "particles/dire_fx/dire_ancient_base001_destruction_k.vpcf", context )
	
	PrecacheResource( "particle", "particles/units/heroes/hero_treant/treant_overgrowth_vine_core_sparkly.vpcf", context )	
	PrecacheResource( "particle", "particles/units/heroes/hero_ursa/ursa_earthshock_rocks.vpcf", context )	
	PrecacheResource( "particle", "particles/units/heroes/hero_warlock/warlock_rain_of_chaos.vpcf", context )	
	PrecacheResource( "particle", "particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis_transform_d.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_witchdoctor/witchdoctor_deathward_glow_b.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_warlock/warlock_rain_of_chaos_start.vpcf", context )
	PrecacheResource( "particle", "particles/items_fx/necronomicon_spawn_warrior_dust.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_life_stealer/life_stealer_rage_end.vpcf", context )
	PrecacheResource( "particle", "particles/holdout_lina/holdout_wildfire_start.vpcf", context )
	PrecacheResource( "particle", "particles/neutral_fx/gnoll_poison_debuff.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_troll_warlord/troll_warlord_battletrance_buff_d.vpcf", context )
	PrecacheResource( "particle", "particles/generic_gameplay/generic_stunned.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_chen/chen_cast_4_d.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_zuus/zuus_arc_lightning_impact.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_legion_commander/legion_commander_press_ribbon.vpcf", context )
	PrecacheResource( "particle", "particles/neutral_fx/ogre_magi_frost_armor_model.vpcf", context )
	PrecacheResource( "particle", "particles/neutral_fx/gnoll_poison_debuff.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_pudge/pudge_rot_body_decay_2.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_pudge/pudge_rot.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_nevermore/nevermore_wings_souls.vpcf", context )
	PrecacheResource( "particle", "particles/items_fx/aura_assault.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_night_stalker/nightstalker_crippling_fear_smoke.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_ogre_magi/ogre_magi_bloodlust_buff_d.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_chen/chen_cast_4_d.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_witchdoctor/witchdoctor_voodoo_restoration_heal.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_phoenix/phoenix_fire_spirit_burn_creep.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_phoenix/phoenix_fire_spirit_ground.vpcf", context )
	PrecacheResource( "particle", "particles/base_attacks/ranged_tower_good.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_troll_warlord/troll_warlord_whirling_axe_melee.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_lina/lina_spell_light_strike_array_explosion.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_dragon_knight/dragon_knight_elder_dragon_frost.vpcf", context )
	
	PrecacheResource( "particle", "particles/units/heroes/hero_sven/sven_warcry_buff_c.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_invoker/invoker_deafening_blast_disarm_c_debuff.vpcf", context )
	PrecacheResource( "particle", "particles/units/heroes/hero_dazzle/dazzle_armor_friend.vpcf", context )
	
	
	-- Precache Sounds
	PrecacheResource( "soundfile", "sounds/physics/damage/building/dire_ancient_destruction_lose.vsnd", context )
	PrecacheResource( "soundfile", "sounds/music/yaskar_01/stingers/radiant_victory.vsnd", context )
	PrecacheResource( "soundfile", "soundevents/game_sounds_custom.vsndevts", context)
	
	-- Building Helper
	-- Model ghost and grid particles
	PrecacheResource("particle_folder", "particles/buildinghelper", context)
	PrecacheResource("particle_folder", "particles/econ/items/earthshaker/earthshaker_gravelmaw/", context)
	PrecacheItemByNameSync("item_apply_modifiers", context)
	
end

-- Create the game mode when we activate
function Activate()
  GameRules.GameMode = GameMode()
  GameRules.GameMode:InitGameMode()
end